### ISSUE TITLE
identify not working

### ISSUE THREAD

**Issue by Ndolam** [Ray-V/tde-slackbuilds#34]
I built tdelibkdcraw-14.1.0-x86_64-1 along with a bunch of otehr 14.1.0 packages.  This produces a program /opt/trinity/bin/identify which runs but is not able to identify any of the image files I have asked it about.

Some people on the TDE users list indicate they don't have an identify from their "full install".  So, I am wondering why this is in the Slackware build, especially in light of the fact that it doesn't seem to work for me.  (Nor did the R14.0.13 version.)

Thoughts?  Thanks.

**Comment by Ray-V** [comment]
>This produces a program /opt/trinity/bin/identify which runs but is not able to identify any of the image files I have asked it about.

That will be because the camera used to take the image isn't supported.  
I found a raw Canon EOS D30 image online, and it displays whatever information is contained in that.  

The source for identify states that it 'emulates dcraw -i', and 'dcraw -i' produces the same information.

libraw is used for TDE and dcraw is a command line decoder and they have slightly different supported cameras lists.  
The supported cameras are listed in libraw_cxx.cpp and dcraw.c [extracted to CameraList].  

There are a couple of posts in the developer mailing list for Nov '22 about upgrading libraw, but to date, nothing further.

>Some people on the TDE users list indicate they don't have an identify from their "full install". So, I am wondering why this is in the Slackware build ..

Because I enabled its installation. The source code is included with libkdcraw and I thought it might be useful, along with the other 'sample' and 'test' programs.

**Comment by Ndolam** [comment]
Thanks Ray.  Perhaps it is just an unfortunate (for me) coincidence that two such radically different (in overall capabilities) have the same name.  Normally I put TDE's bin directory ahead of /usr/bin, but in this case that doesn't work out well.  Easy enough to delete/rename/chmod the TDE identify.

Cheers.
