### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by fastname3** [Ray-V/tde-slackbuilds#5]
Hello again
What happened with Thorn?
You also go or continue with the tde-slackbuilds?

**Comment by Ray-V** [comment]
I don't know what happened. I got notification that he'd closed issues 47 & 48 and all seemed normal, and then a few hours later, his GitHub account disappeared.

I'd created this fork for pull requests. It was up to date to 2017-08-03, so I added the cpu optimization changes I'd made - that was #46.

Then there was issue 47 - a Spanish translation for kvkbd and that krusader was building all translations even if only one was required. I don't know the details of what was done for issue 47, but I know what needs to be done so I'll sort that out and I'll keep this repository available ..

Issue 48 was the one you raised which turned out to be an outstanding development issue. I did build tdebase and tdelibs development versions from a 2017-05-xx git download I had on disk, and it does mount encrypted pen drives but it crashes when trying to eject them - but maybe that's been fixed by now, or I missed something?

**Comment by fastname3** [comment]
What mysteries disappear with how well it went

I can help you by trying but this code you have here does not work for me,
ask for some includes that I do not have.

I'm trying out these another scripts here updating them to 14.0.4
http://www.giustetti.net/wiki/index.php?title=En/trinity_desktop_environment_14.0.0#Package_SlackBuild_script
I compiled tde-base and tde-libs but does not resolve the issue "Not all mimetypes are detected" :(

Why a translation in Spanish, you speak Spanish?

If crashes when you take it down is bad not fixed :)

See you

**Comment by Ray-V** [comment]
>*I can help you by trying but this code you have here does not work for me, ask for some includes that I do not have.*

What includes? If the build from Thorn-Inurcide/tde-slackbuilds worked for you, when did you download it? If it doesn't work now, then it must be because of something added since then.

>*I compiled tde-base and tde-libs but does not resolve the issue "Not all mimetypes are detected"*

Where does this message come up? Give some examples of mimetypes you want detected.

>*Why a translation in Spanish, you speak Spanish?*

No, but Thorn wanted to include it.

>*If crashes when you take it down is bad not fixed.*

I don't think so - it's only development code from May 2017 that I tried. It might be fixed by now, or the build needs something I've missed out. I didn't go any further than that because it's an upcoming feature and I'm not a programmer.

**Comment by fastname3** [comment]
I do not remember what includes asked
I download from here from your github.com/Ray-V/tde-slackbuilds/
you code still depends of avahi, that was before i think

Is not a message does not detect them as always, plaintext, text, scripts, etc
Look at the file KNOWN-ISSUES 

I'm not a programmer neither.

I've added knetstat and tdetheme in the code and they are doing well,
I will add some more apps when I have time.
